name: Build Performance

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-time:
    name: Build Time Performance
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Installation
        run: npm install


      - name: Build (cold cache)
        run: npm run build
        timeout-minutes: 5

      - name: Build (warm cache)
        run: npm run build
        timeout-minutes: 2
